export default {
	extends: ['@commitlint/config-conventional'],
	rules: {
		'type-enum': [
			2,
			'always',
			[
				'feat',
				'fix',
				'refactor',
				'perf',
				'docs',
				'style',
				'test',
				'build',
				'ci',
				'chore',
				'revert',
			],
		],
		'scope-empty': [2, 'never'],
		'scope-enum': [
			2,
			'always',
			[
				'core',
				'ui',
				'api',
				'db',
				'auth',
				'config',
				'deps',
				'types',
				'utils',
				'docs',
				'tests',
				'ci',
				'release',
			],
		],
		'subject-empty': [2, 'never'],
		'subject-case': [2, 'always', ['lower-case', 'sentence-case']],
		'header-max-length': [2, 'always', 100],
		'subject-full-stop': [2, 'never', '.'],
	},
};
