/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false wrangler.d.ts` (hash: 91f087a8d7b8f046b083891cef792f78)
interface __BaseEnv_Env {
	SESSION: KVNamespace;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
