import { createHash } from 'node:crypto';
import { readdir, readFile, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseFrontmatter } from '@astrojs/markdown-remark';
import { parse, type DefaultTreeAdapterMap } from 'parse5';

type Element = DefaultTreeAdapterMap['element'];
type Node = DefaultTreeAdapterMap['document'] | DefaultTreeAdapterMap['childNode'];
type Artifact = { slug: string; public: boolean; published: string; modified: string; updatedAt?: string };
const GENERATED_HEADERS = '# Article export rules generated by scripts/output.ts';
const PUBLIC_TEXT_FILES = new Set(['llms.txt', 'robots.txt']);

function assert(condition: unknown, message: string): asserts condition {
	if (!condition) throw new Error(message);
}

function elements(node: Node): Element[] {
	const found: Element[] = 'tagName' in node ? [node] : [];
	if ('childNodes' in node) {
		for (const child of node.childNodes) found.push(...elements(child));
	}
	return found;
}

function attributes(element: Element): Record<string, string> {
	return Object.fromEntries(element.attrs.map(({ name, value }) => [name, value]));
}

function digest(source: string | Buffer, algorithm: 'sha256' | 'sha512'): string {
	return `${algorithm}-${createHash(algorithm).update(source).digest('base64')}`;
}

async function isFile(filePath: string): Promise<boolean> {
	return stat(filePath)
		.then((info) => info.isFile())
		.catch(() => false);
}

async function filesIn(directory: string): Promise<string[]> {
	const files: string[] = [];
	for (const item of await readdir(directory, { withFileTypes: true })) {
		const filePath = path.join(directory, item.name);
		if (item.isDirectory()) files.push(...(await filesIn(filePath)));
		else if (item.isFile()) files.push(filePath);
	}
	return files;
}

export function headersForPath(source: string, pathname: string): Map<string, string> {
	const headers = new Map<string, string>();
	let matches = false;
	for (const line of source.split(/\r?\n/)) {
		if (!line.trim() || line.startsWith('#')) continue;
		if (!/^\s/.test(line)) {
			// Host-specific preview rules do not apply to the canonical site.
			const pattern = line.trim();
			const escaped = pattern.replace(/[.+?^${}()|[\]\\]/g, '\\$&').replaceAll('*', '.*');
			matches = pattern.startsWith('/') && new RegExp(`^${escaped}$`).test(pathname);
			continue;
		}
		if (!matches) continue;
		const header = line.trim();
		if (header.startsWith('! ')) {
			headers.delete(header.slice(2).toLowerCase());
			continue;
		}
		const colon = header.indexOf(':');
		assert(colon > 0, `Invalid header line: ${header}`);
		const name = header.slice(0, colon).toLowerCase();
		const value = header.slice(colon + 1).trim();
		headers.set(name, headers.has(name) ? `${headers.get(name)}, ${value}` : value);
	}
	return headers;
}

function cspSources(csp: string, directive: string): string[] {
	const directives = new Map(
		csp.split(';').map((value) => {
			const [name = '', ...sources] = value.trim().split(/\s+/);
			return [name, sources] as const;
		}),
	);
	return directives.get(directive) ?? (directive === 'script-src-elem' ? directives.get('script-src') : undefined) ?? directives.get('default-src') ?? [];
}

export function assertCspUrl(csp: string, directive: string, value: string, origin: string): void {
	const url = new URL(value, origin);
	const allowed = cspSources(csp, directive).some((source) => source === '*' || source === url.protocol || (source === "'self'" && url.origin === origin) || source === url.origin);
	assert(allowed, `${directive} blocks ${url.origin === 'null' ? url.protocol : url.origin}; update the media configuration or public/_headers`);
}

export async function validateHtml(source: string, filePath: string, directory: string, csp: string, origin: string): Promise<void> {
	const nodes = elements(parse(source));
	for (const node of nodes) {
		const attrs = attributes(node);
		const src = attrs['src'];
		if (node.tagName === 'script') {
			if (src) {
				assertCspUrl(csp, 'script-src-elem', src, origin);
				if (src === '/boot.js') {
					const expected = digest(await readFile(path.join(directory, 'boot.js')), 'sha512');
					assert(attrs['integrity'] === expected, `${filePath}: boot.js integrity does not match the final script`);
				}
			} else if (!attrs['type'] || attrs['type'] === 'module' || attrs['type'] === 'text/javascript') {
				const script = node.childNodes.map((child) => ('value' in child ? child.value : '')).join('');
				assert(cspSources(csp, 'script-src-elem').includes(`'${digest(script, 'sha256')}'`), `${filePath}: inline script is missing its CSP hash`);
			}
		}
		const media = src ?? attrs['data-src'];
		if (media && ['img', 'video', 'audio', 'source'].includes(node.tagName)) {
			const isImage = node.tagName === 'img' || (node.tagName === 'source' && node.parentNode !== null && 'tagName' in node.parentNode && node.parentNode.tagName === 'picture');
			assertCspUrl(csp, isImage ? 'img-src' : 'media-src', media, origin);
		}
		if (attrs['poster']) assertCspUrl(csp, 'img-src', attrs['poster'], origin);
		if (attrs['data-hover-preview-src']) assertCspUrl(csp, attrs['data-hover-preview-kind'] === 'video' ? 'media-src' : 'img-src', attrs['data-hover-preview-src'], origin);
		const socialImage = node.tagName === 'meta' && (attrs['property'] === 'og:image' || attrs['name'] === 'twitter:image') ? attrs['content'] : undefined;
		for (const candidate of [src, attrs['href'], attrs['poster'], attrs['data-src'], socialImage]) {
			if (!candidate || candidate.startsWith('#')) continue;
			const relativePage = path.relative(directory, filePath).replaceAll(path.sep, '/');
			const url = new URL(candidate, `${origin}/${relativePage}`);
			if (url.origin !== origin) continue;
			const localPath = path.join(directory, decodeURIComponent(url.pathname));
			assert((await isFile(localPath)) || (await isFile(path.join(localPath, 'index.html'))), `${filePath}: missing local target ${url.pathname}`);
		}
	}
}

function assertSamePaths(actual: string[], expected: string[], label: string): void {
	assert(new Set(actual).size === actual.length, `${label}: duplicate artifact paths`);
	assert(JSON.stringify(actual.toSorted()) === JSON.stringify(expected.toSorted()), `${label}: public artifact paths differ\nexpected: ${expected.join(', ')}\nactual: ${actual.join(', ')}`);
}

async function readArtifacts(directory: string): Promise<Artifact[]> {
	const artifacts: Artifact[] = [];
	for (const filePath of await filesIn(directory)) {
		if (!filePath.endsWith('.mdx')) continue;
		const data: Record<string, unknown> = parseFrontmatter(await readFile(filePath, 'utf8')).frontmatter;
		assert(typeof data['slug'] === 'string' && /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(data['slug']), `${filePath}: invalid artifact slug`);
		const date = data['date'];
		const updatedAt = data['updatedAt'] ?? date;
		assert(typeof date === 'string' || date instanceof Date, `${filePath}: missing publication date`);
		assert(typeof updatedAt === 'string' || updatedAt instanceof Date, `${filePath}: invalid modification date`);
		artifacts.push({
			slug: data['slug'],
			public: data['isArtifactItem'] !== false && !(data['type'] === 'study' && data['isConfidential'] === true),
			published: new Date(date).toISOString(),
			modified: new Date(updatedAt).toISOString(),
			...(data['updatedAt'] === undefined ? {} : { updatedAt: new Date(updatedAt).toISOString() }),
		});
	}
	return artifacts;
}

export function articleHeaders(source: string, slugs: string[]): string {
	const base = source.split(GENERATED_HEADERS)[0]?.trimEnd() ?? '';
	const rules = slugs.toSorted().flatMap((slug) => ['md', 'txt'].map((extension) => `/${slug}.${extension}\n  X-Robots-Tag: noindex`));
	return `${base}\n\n${GENERATED_HEADERS}\n${rules.join('\n\n')}\n`;
}

export async function validateBuildOutput(directory: string, artifacts: Artifact[]): Promise<void> {
	const publicSlugs = artifacts.filter((artifact) => artifact.public).map((artifact) => artifact.slug);
	const allFiles = await filesIn(directory);
	const relativeFiles = allFiles.map((filePath) => path.relative(directory, filePath).replaceAll(path.sep, '/'));
	assertSamePaths(
		relativeFiles.filter((name) => name.endsWith('.md')).map((name) => name.slice(0, -3)),
		publicSlugs,
		'Markdown exports',
	);
	assertSamePaths(
		relativeFiles.filter((name) => name.endsWith('.txt') && !PUBLIC_TEXT_FILES.has(name)).map((name) => name.slice(0, -4)),
		publicSlugs,
		'Text exports',
	);
	assertSamePaths(
		relativeFiles.filter((name) => name.endsWith('/index.html')).map((name) => name.slice(0, -11)),
		publicSlugs,
		'Article HTML',
	);
	const headers = await readFile(path.join(directory, '_headers'), 'utf8');
	const csp = headersForPath(headers, '/').get('content-security-policy');
	assert(csp, 'Built output has no Content-Security-Policy');
	const home = elements(parse(await readFile(path.join(directory, 'index.html'), 'utf8')));
	const canonical = home.map(attributes).find((attrs) => attrs['rel'] === 'canonical')?.['href'];
	assert(canonical, 'Homepage has no canonical URL');
	const origin = new URL(canonical).origin;
	const mediaBase = process.env['PUBLIC_MEDIA_BASE_URL'];
	if (mediaBase) {
		assertCspUrl(csp, 'img-src', mediaBase, origin);
		assertCspUrl(csp, 'media-src', mediaBase, origin);
	}
	assert((await readFile(path.join(directory, 'boot.js'), 'utf8')).trim().length > 0, 'Built boot.js is empty');
	for (const filePath of allFiles.filter((name) => name.endsWith('.html'))) {
		const html = await readFile(filePath, 'utf8');
		assert(!html.includes('/fonts/'), `${filePath}: font URLs must use fingerprinted build assets`);
		if (path.basename(filePath) === 'index.html')
			assert(
				elements(parse(html)).some((node) => node.tagName === 'script' && attributes(node)['src'] === '/boot.js'),
				`${filePath}: missing boot script`,
			);
		await validateHtml(html, filePath, directory, csp, origin);
	}
	for (const filePath of allFiles.filter((name) => name.endsWith('.css'))) {
		const css = await readFile(filePath, 'utf8');
		assert(!css.includes('/fonts/'), `${filePath}: font URLs must use fingerprinted build assets`);
		for (const match of css.matchAll(/url\(\s*['"]?([^'"\s)]+)['"]?\s*\)/g)) {
			const value = match[1];
			if (!value || value.startsWith('data:')) continue;
			const cssUrl = `${origin}/${path.relative(directory, filePath).replaceAll(path.sep, '/')}`;
			const url = new URL(value, cssUrl);
			if (url.origin === origin) assert(await isFile(path.join(directory, decodeURIComponent(url.pathname))), `${filePath}: missing CSS asset ${url.pathname}`);
		}
	}
	const feed: unknown = JSON.parse(await readFile(path.join(directory, 'feed.json'), 'utf8'));
	assert(typeof feed === 'object' && feed !== null && 'items' in feed && Array.isArray(feed.items), 'Invalid JSON Feed');
	const itemUrls: string[] = feed.items.map((item: unknown) => {
		assert(typeof item === 'object' && item !== null && 'url' in item && typeof item.url === 'string', 'Invalid JSON Feed item');
		const artifact = artifacts.find((entry) => item.url === `${origin}/${entry.slug}/`);
		assert(artifact && 'date_published' in item && item.date_published === artifact.published, `${item.url}: JSON Feed publication date differs from content`);
		if (artifact.updatedAt === undefined) {
			assert(!('date_modified' in item), `${item.url}: JSON Feed invents a modification date absent from content`);
		} else {
			assert('date_modified' in item && item.date_modified === artifact.updatedAt, `${item.url}: JSON Feed modification date differs from content`);
		}
		return item.url;
	});
	const expectedUrls = publicSlugs.map((slug) => `${origin}/${slug}/`);
	assertSamePaths(itemUrls, expectedUrls, 'JSON Feed');
	const rss = await readFile(path.join(directory, 'rss.xml'), 'utf8');
	assertSamePaths(
		[...rss.matchAll(/<guid\b[^>]*>([^<]+)<\/guid>/g)].map((match) => match[1] ?? ''),
		expectedUrls,
		'RSS',
	);
	const sitemap = await readFile(path.join(directory, 'sitemap.xml'), 'utf8');
	const sitemapUrls = [...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map((match) => match[1] ?? '');
	assertSamePaths(sitemapUrls, [origin + '/', ...['llms.txt', 'rss.xml', 'feed.json'].map((name) => `${origin}/${name}`), ...expectedUrls], 'Sitemap');
	const sitemapDates = new Map([...sitemap.matchAll(/<url>([\s\S]*?)<\/url>/g)].map((match) => [match[1]?.match(/<loc>([^<]+)<\/loc>/)?.[1], match[1]?.match(/<lastmod>([^<]+)<\/lastmod>/)?.[1]]));
	for (const artifact of artifacts.filter((entry) => entry.public))
		assert(sitemapDates.get(`${origin}/${artifact.slug}/`) === artifact.modified, `${artifact.slug}: sitemap modification date differs from content`);
	const homeModified = sitemapDates.get(origin + '/');
	assert(homeModified && Number.isFinite(Date.parse(homeModified)), 'Sitemap homepage has no valid modification date');
	const latestModified = Math.max(Date.parse(homeModified), ...artifacts.filter((entry) => entry.public).map((entry) => Date.parse(entry.modified)));
	assert(Date.parse(rss.match(/<lastBuildDate>([^<]+)<\/lastBuildDate>/)?.[1] ?? '') === latestModified, 'RSS build date does not reflect the latest modification');
	const llms = await readFile(path.join(directory, 'llms.txt'), 'utf8');
	for (const slug of publicSlugs) {
		const markdown = await readFile(path.join(directory, `${slug}.md`), 'utf8');
		assert(markdown === (await readFile(path.join(directory, `${slug}.txt`), 'utf8')), `${slug}: Markdown and text exports differ`);
		assert(llms.includes(markdown.trim()), `${slug}: llms.txt is missing the article export`);
		for (const extension of ['md', 'txt']) assert(headersForPath(headers, `/${slug}.${extension}`).get('x-robots-tag') === 'noindex', `${slug}.${extension}: missing static noindex header`);
	}
	for (const name of PUBLIC_TEXT_FILES) assert(!headersForPath(headers, `/${name}`).has('x-robots-tag'), `${name}: article export policy leaked into public discovery text`);
	for (const artifact of artifacts.filter((entry) => !entry.public)) assert(!llms.includes(`${origin}/${artifact.slug}/`), `${artifact.slug}: nonpublic artifact leaked into llms.txt`);
}

export async function prepareBuildOutput(root = process.cwd()): Promise<void> {
	const directory = path.join(root, 'dist/client');
	const artifacts = await readArtifacts(path.join(root, 'src/content'));
	const headersPath = path.join(directory, '_headers');
	const builtHeaders = await readFile(headersPath, 'utf8');
	await writeFile(
		headersPath,
		articleHeaders(
			builtHeaders,
			artifacts.filter((artifact) => artifact.public).map((artifact) => artifact.slug),
		),
	);
	await validateBuildOutput(directory, artifacts);
	console.log(`Validated build output, CSP, integrity, local links, and ${artifacts.filter((artifact) => artifact.public).length} public artifact exports.`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
	await prepareBuildOutput();
}
